
CREATE TABLE DIET_DIARY_MEMBERS(
	  DIET_DIARY_MEMBERS_IDX NUMBER PRIMARY KEY
	, ID VARCHAR2(30) UNIQUE NOT NULL
	, PASS VARCHAR2(64) NOT NULL
	, NAME VARCHAR2(30) UNIQUE NOT NULL
	, REGDATE DATE DEFAULT SYSDATE
	, QUESTION NUMBER
	, ANSWER VARCHAR2(64)
);

CREATE SEQUENCE SEQ_DIET_DIARY_MEMBERS
INCREMENT BY 1
START WITH 1;


SELECT TABLE_NAME FROM USER_TABLES;
SELECT SEQUENCE_NAME FROM USER_SEQUENCES;

DROP TABLE DIET_DIARY_MEMBERS;
DROP SEQUENCE seq_diet_diary_members;